name: Release
permissions:
  contents: write

on:
    workflow_dispatch:
        inputs:
            version:
                description: Version to release
                default: v1.0.0
                required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create version number
        run: echo ${{ github.event.inputs.version }} | sed 's/^v//' > build/package/version.txt

      - name: Configure CMake
        run: cmake -B build/package -DPROJECT_VERSION:STRING=$(cat build/package/version.txt)

      - name: Package source code
        run: cmake --build build/package --target wite_package

      - name: Pack NuGet package
        run: |
          cp README.md packaging/README.md
          sed -i '/!\[Ubuntu \| GCC12 \| x64 \| Debug\]/d' packaging/README.md
          sed -i '/!\[Ubuntu \| GCC12 \| x64 \| Release\]/d' packaging/README.md
          sed -i '/!\[Windows \| MSCV++ \| x64 \| Debug\]/d' packaging/README.md
          sed -i '/!\[Windows \| MSCV++ \| x64 \| Release\]/d' packaging/README.md
          
          nuget pack packaging/wite.nuspec -Properties version=$(cat build/package/version.txt) -OutputDirectory build/package

      - name: Add packaged source code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: build/package/wite*
          tag: ${{ github.event.inputs.version }}
          overwrite: true