name: Release
permissions:
  contents: write

on:
    workflow_dispatch:
        inputs:
            git-ref:
                description: Commit to release
                required: false
            version:
                description: Version to release
                default: v1.0.0
                required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build

      - name: Package source code
        run: cmake --build build --target wite_package

      - name: Add packaged source code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/wite-src.zip
          tag: ${{ github.event.inputs.version }}