name: Release
permissions:
  contents: write

on:
    workflow_dispatch:
        inputs:
            git-ref:
                description: Tag to release
                required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Package source code
        working-directory: .
        run: cmake --build --target wite_package

      - name: Add packaged source code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/wite-src.zip
          tag: ${{ github.ref }}